"""Text embeddings generated by Aila Nano itself.

Rather than depending on an external embedding API, this module reuses
the pretrained Aila Nano transformer's own hidden states: mean-pool the
final-norm hidden states over non-padding tokens to get a fixed-size,
L2-normalized vector per text. This keeps the whole stack — generation
*and* semantic search — powered by one original model.
"""

from __future__ import annotations

import numpy as np
import torch

from model.transformer import AilaNanoGPT
from tokenizer.tokenizer import AilaTokenizer


class AilaEmbedder:
    def __init__(
        self,
        model: AilaNanoGPT,
        tokenizer: AilaTokenizer,
        device: str = "cpu",
        max_len: int | None = None,
    ):
        self.model = model.to(device)
        self.model.eval()
        self.tokenizer = tokenizer
        self.device = device
        self.max_len = max_len or model.cfg.max_seq_len

    @property
    def dim(self) -> int:
        return self.model.cfg.d_model

    @torch.no_grad()
    def embed(self, texts: str | list[str]) -> np.ndarray:
        """Returns an (n, d_model) float32 array of L2-normalized embeddings."""
        single = isinstance(texts, str)
        if single:
            texts = [texts]

        batch_ids = [
            self.tokenizer.encode(t, add_bos=True, add_eos=True)[: self.max_len] for t in texts
        ]
        max_len = max(len(ids) for ids in batch_ids)
        pad_id = self.tokenizer.pad_id

        input_ids = torch.full((len(batch_ids), max_len), pad_id, dtype=torch.long)
        mask = torch.zeros((len(batch_ids), max_len), dtype=torch.bool)
        for i, ids in enumerate(batch_ids):
            input_ids[i, : len(ids)] = torch.tensor(ids, dtype=torch.long)
            mask[i, : len(ids)] = True
        input_ids = input_ids.to(self.device)
        mask = mask.to(self.device)

        hidden = self.model.forward_hidden(input_ids)  # (n, seq, d_model)
        mask_f = mask.unsqueeze(-1).float()
        pooled = (hidden * mask_f).sum(dim=1) / mask_f.sum(dim=1).clamp(min=1.0)

        vecs = pooled.cpu().numpy().astype(np.float32)
        norms = np.linalg.norm(vecs, axis=1, keepdims=True)
        norms[norms == 0] = 1.0
        vecs = vecs / norms
        return vecs
